artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: data/mimic-iii-clinical-db.zip
  unzip_dir: artifacts/data_ingestion


patients_representation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/mimic-iii-clinical-database/PATIENTS.csv
  taxonomy: Patient
  sub_taxonomy: Entity
  column_id: subject_id
  attributs:
    attribut0: subject_id
    attribut1: gender
    attribut2: dob
    attribut3: dod
    attribut3: dod_hosp
    attribut3: dod_ssn
    attribut3: expire_flag

event_logs:
  root_dir: artifacts/event_logs/
  subjectids: artifacts/data_ingestion/mimic-iii-clinical-database/PATIENTS.csv 
  identifier: subject_id  
  logs:
    log1: artifacts/data_ingestion/mimic-iii-clinical-database/OUTPUTEVENTS.csv
    log2: artifacts/data_ingestion/mimic-iii-clinical-database/CHARTEVENTS.csv
    log3: artifacts/data_ingestion/mimic-iii-clinical-database/INPUTEVENTS_CV.csv
    log4: artifacts/data_ingestion/mimic-iii-clinical-database/INPUTEVENTS_MV.csv
    log5: artifacts/data_ingestion/mimic-iii-clinical-database/LABEVENTS.csv
    log6: artifacts/data_ingestion/mimic-iii-clinical-database/MICROBIOLOGYEVENTS.csv
  patient_attributs:
    attribut1: subject_id 
    attribut2: hadm_id
    attribut3: admittime
    attribut4: dischtime
    attribut5: deathtime
    attribut6: admission_type
    attribut7: admission_location
    attribut8: discharge_location
    attribut9: insurance
    attribut10: language
    attribut11: religion
    attribut12: marital_status
    attribut13: ethnicity
    attribut14: edregtime
    attribut15: edouttime
    attribut16: diagnosis
    attribut17: hospital_expire_flag
    attribut18: has_chartevents_data
    attribut19: submit_wardid
    attribut20: submit_careunit
    attribut21: curr_wardid
    attribut22: curr_careunit
    attribut23: callout_wardid
    attribut24: callout_service
    attribut25: request_tele
    attribut26: request_resp
    attribut27: request_cdiff
    attribut28: request_mrsa
    attribut29: request_vre
    attribut30: callout_status
    attribut31: callout_outcome
    attribut32: discharge_wardid
    attribut33: acknowledge_status
    attribut34: createtime
    attribut35: updatetime
    attribut36: acknowledgetime
    attribut37: outcometime
    attribut38: firstreservationtime
    attribut39: currentreservationtime 
    attribut40: icustay_id
    attribut41: charttime
    attribut42: itemid
    attribut43: value
    attribut44: valueuom
    attribut45: storetime
    attribut46: cgid
    attribut47: stopped
    attribut48: newbottle
    attribut49: iserror
    attribut50: gender
    attribut51: dob
    attribut52: dod
    attribut53: dod_hosp
    attribut54: dod_ssn
    attribut55: expire_flag
    attribut56: costcenter
    attribut57: chartdate
    attribut58: cpt_cd
    attribut59: cpt_suffix
    attribut60: ticket_id_seq
    attribut61: sectionheader
    attribut62: subsectionheader
    attribut63: description
    attribut64: dbsource
    attribut65: first_careunit
    attribut66: last_careunit
    attribut67: first_wardid
    attribut68: last_wardid
    attribut69: intime
    attribut70: outtime
    attribut71: los
    attribut72: amount
    attribut73: amountuom
    attribut74: rate
    attribut75: rateuom
    attribut76: storetime
    attribut77: orderid
    attribut78: linkorderid
    attribut79: stopped
    attribut80: newbottle
    attribut81: originalamount
    attribut82: originalamountuom
    attribut83: originalroute
    attribut84: originalrate
    attribut85: originalrateuom
    attribut86: originalsite
    attribut87: starttime
    attribut88: endtime
    attribut89: ordercategoryname
    attribut90: secondaryordercategoryname
    attribut91: ordercomponenttypedescription
    attribut92: ordercategorydescription
    attribut93: patientweight
    attribut94: totalamount
    attribut95: totalamountuom
    attribut96: isopenbag
    attribut97: continueinnextdept
    attribut98: cancelreason
    attribut99: statusdescription
    attribut100: comments_editedby
    attribut101: comments_canceledby
    attribut102: comments_date
    attribut103: originalamount
    attribut104: originalrate
    attribut105: value
    attribut106: valuenum
    attribut107: valueuom
    attribut108: flag
    attribut109: spec_itemid
    attribut110: spec_type_desc
    attribut111: org_itemid
    attribut112: org_name
    attribut113: isolate_num
    attribut114: ab_itemid
    attribut115: ab_name
    attribut116: dilution_text
    attribut117: dilution_comparison
    attribut118: dilution_value
    attribut119: interpretation
    attribut120: startdate
    attribut121: enddate
    attribut122: drug_type
    attribut123: drug
    attribut124: drug_name_poe
    attribut125: drug_name_generic
    attribut126: formulary_drug_cd
    attribut127: gsn
    attribut128: ndc
    attribut129: prod_strength
    attribut130: dose_val_rx
    attribut131: dose_unit_rx
    attribut132: form_val_disp
    attribut133: form_unit_disp
    attribut134: route
    attribut135: eventtype
    attribut136: prev_careunit
    attribut137: curr_careunit
    attribut138: prev_wardid
    attribut139: transfertime
    attribut140: prev_service
    attribut141: curr_service
    attribut142: location
    attribut143: locationcategory
    attribut144: value
    attribut145: warning
    attribut146: error
    attribut147: resultstatus

events_representation:
  data_path: artifacts/event_logs/
  taxonomy: Event
  sub_taxonomy: Event
  column_id: subject_id
  space: charttime
  time: charttime
  relation: DIRECTLY_FOLLOW
  event_attributs:
    attribut1: hadm_id
    attribut2: edregtime
    attribut3: edouttime
    attribut4: diagnosis
    attribut7: submit_wardid
    attribut8: submit_careunit
    attribut9: curr_wardid
    attribut10: curr_careunit
    attribut11: callout_wardid
    attribut12: callout_service
    attribut13: request_tele
    attribut14: request_resp
    attribut15: request_cdiff
    attribut16: request_mrsa
    attribut17: request_vre
    attribut18: callout_status
    attribut19: callout_outcome
    attribut20: createtime
    attribut21: updatetime
    attribut22: acknowledgetime
    attribut23: outcometime
    attribut24: firstreservationtime
    attribut25: currentreservationtime 
    attribut26: icustay_id
    attribut27: itemid
    attribut28: value
    attribut29: valueuom
    attribut30: storetime
    attribut31: cgid
    attribut32: stopped
    attribut33: newbottle
    attribut34: iserror
    attribut35: costcenter
    attribut36: chartdate
    attribut37: cpt_cd
    attribut38: cpt_suffix
    attribut39: ticket_id_seq
    attribut40: sectionheader
    attribut41: subsectionheader
    attribut42: description
    attribut43: dbsource
    attribut44: first_careunit
    attribut45: last_careunit
    attribut46: first_wardid
    attribut47: last_wardid
    attribut48: intime
    attribut49: outtime
    attribut50: los
    attribut51: amount
    attribut52: amountuom
    attribut53: rate
    attribut54: rateuom
    attribut55: storetime
    attribut56: orderid
    attribut57: linkorderid
    attribut58: stopped
    attribut59: newbottle
    attribut60: originalamount
    attribut61: originalamountuom
    attribut62: originalroute
    attribut63: originalrate
    attribut64: originalrateuom
    attribut65: originalsite
    attribut66: starttime
    attribut67: endtime
    attribut68: ordercategoryname
    attribut69: secondaryordercategoryname
    attribut70: ordercomponenttypedescription
    attribut71: ordercategorydescription
    attribut72: patientweight
    attribut73: totalamount
    attribut74: totalamountuom
    attribut75: isopenbag
    attribut76: continueinnextdept
    attribut77: cancelreason
    attribut78: statusdescription
    attribut79: comments_editedby
    attribut80: comments_canceledby
    attribut81: comments_date
    attribut82: originalamount
    attribut83: originalrate
    attribut84: value
    attribut85: valuenum
    attribut86: valueuom
    attribut87: flag
    attribut88: spec_itemid
    attribut89: spec_type_desc
    attribut90: org_itemid
    attribut91: org_name
    attribut92: isolate_num
    attribut93: ab_itemid
    attribut94: ab_name
    attribut95: dilution_text
    attribut96: dilution_comparison
    attribut97: dilution_value
    attribut98: interpretation
    attribut99: startdate
    attribut100: enddate
    attribut101: drug_type
    attribut102: drug
    attribut103: drug_name_poe
    attribut104: drug_name_generic
    attribut105: formulary_drug_cd
    attribut106: gsn
    attribut107: ndc
    attribut108: prod_strength
    attribut109: dose_val_rx
    attribut110: dose_unit_rx
    attribut111: form_val_disp
    attribut112: form_unit_disp
    attribut113: route
    attribut114: eventtype
    attribut115: prev_careunit
    attribut116: curr_careunit
    attribut117: prev_wardid
    attribut118: transfertime
    attribut119: prev_service
    attribut120: curr_service
    attribut121: location
    attribut122: locationcategory
    attribut123: value
    attribut124: warning
    attribut125: error
    attribut126: resultstatus
    attribut127: subject_id 
  patient_attributs:
    attribut1: admittime
    attribut2: dischtime
    attribut3: deathtime
    attribut4: admission_type
    attribut5: admission_location
    attribut6: discharge_location
    attribut7: insurance
    attribut8: language
    attribut9: religion
    attribut10: marital_status
    attribut11: ethnicity
    
event_relationships:
  subjectids_path: artifacts/data_ingestion/mimic-iii-clinical-database/PATIENTS.csv 
  identifier: subject_id
  taxonomy: Event
  sub_taxonomy: Event
  key: subject_id
  time: charttime
  type_relation: DIRECTLY_FOLLOW

entity_relationships:
  subjectids_path: artifacts/data_ingestion/mimic-iii-clinical-database/PATIENTS.csv
  identifier: subject_id 
  type_relation: HAS_EVENT
  entity_taxonomy: Patient
  event_taxonomy: Event
  key: subject_id

class_relationships:
  subjectids_path: artifacts/data_ingestion/mimic-iii-clinical-database/PATIENTS.csv
  identifier: subject_id 
  type_relation: HAS_CLASS
  entity_taxonomy: Patient
  event_taxonomy: Event
  key: subject_id
  check_attribut: dod

resource_relationships:
  resources_path: artifacts/data_ingestion/mimic-iii-clinical-database/SERVICES.csv 
  subjectids_path: artifacts/data_ingestion/mimic-iii-clinical-database/PATIENTS.csv
  identifier: subject_id 
  type_relation: HAS_SERVICES
  event_taxonomy: Event
  key: subject_id

events_optimization:
  subjectids_path: artifacts/data_ingestion/mimic-iii-clinical-database/PATIENTS.csv
  identifier: subject_id 
  event_taxonomy: Event
  key: subject_id